### PR TITLE
Parse N1 fields individually

### PR DESCRIPTION
**Pull request by mcallaghan**
When working with exported RIS files, other fields such as reference lists are listed in the N1 field. I prefer to access them as fields in their own right

### CODE REVIEW

**Comment by shapiromatron** [comment]
Thanks for the PR! The fields here look like they're in a different format than most of the other fields in RIS - could you point me towards where the format is specified for the new fields?

**Comment by mcallaghan** [comment]
I haven't specified the format except for those which are list fields. Can't see an equivalent other format specification for other field types in your existing code, unless you mean format specification in some kind of standard?

For me they usually look like this (a RIS export from scopus):

```
N1  - Correspondence Address: Parchuk, G.V.; Hydrobiological Institute, National Academy of Sciences, Kiev, Ukraine
N1  - References: Avakyan, A.B., Saltankin, V.P., Sharapov, V.A., (1987) Bodokhranilishche (The Reservoir), , Mysl Press, Moscow; 
Alekseyev, V.R., How intensification measures influence zooplankton abundance and seasonal crustacean cycles in lakes used for raising coregonids (1987) Tr. Gos. NII Ozer. i Rech. Ryb. Khozva, (264), pp. 20-32; 
Andreyuk, Ye.I., Kopteva, Zh.P., Zanina, V.V., (1990) Tsianobakterii (The Cyanobacteria), , Naukova Dumka Press, Kiev; 
Braginskiy, L.P., (1972) Pestitsidy i Zhizn' Vodoyemov (Pesticides and the Life of Natural Waters), , Naukova Dumka Press, Kiev; 
```

I don't know if this is defined somewhere anywhere though...

**Comment by shapiromatron** [comment]
Gotcha, I guess I'm trying to determine if this scopus implementation is part of the RIS standard or just how it was implemented by scopus and may not be followed by others. I don't really see it documented here: https://en.wikipedia.org/wiki/RIS_(file_format). 

Perhaps it would make more sense to make a new config for scopus that could be used instead of the default RIS config? Do you think the code could be modified so that it'd be a separate config that could be loaded when using scopus data?  With some unit tests too please :)

**Comment by mcallaghan** [comment]
Yep, I'm pretty sure it is _not_ part of the RIS standard. Rather, it is Scopus' way of shoehorning in extra information which does not fit into the standard. Had assumed this was common practice but it may indeed (at least in this format) be limited to Scopus.

In this case I agree it would make sense to make a config for scopus - Will have a look next week.

**Comment by shapiromatron** [comment]
@mcallaghan will close this PR for now; feel free to resubmit after you've reworked it!

**Pull request closed without merging**
