### PR TITLE
A litle more pythonic

### PR DESCRIPTION
**Pull request by sacabuche**
Make code more pythonic and add the posibility to only pass  lines of content, no need to pass a file.

Also suport for python 3.5

### CODE REVIEW

**Comment by timflutre** [comment]
Commits from this pull request also smoothly handle the case of unknown fields by ignoring them, whereas the current package returns an error: thanks @sacabuche !

**Comment by sacabuche** [comment]
Let me check on that, does this happen using the test suit?

**Comment by timflutre** [comment]
I didn't run the test suite. I only used your code on a RIS file of mine, and saw lines like this on stdout:
('RIS Ignored:', 'L3  - citeulike-article-id:3394146\r\n')
The execution carries on, so it's much better than stopping with an error, but maybe a warning would be more appropriate?

**Comment by sacabuche** [comment]
I think that may be the better is to keep the field and print a warning, what do you think?

**Comment by timflutre** [comment]
Yes, I agree.

**Comment by timflutre** [comment]
@sacabuche it seems that the code can't handle multi-line fields. As it looks like @MrTango doesn't have time to pursue this RISparser project, would you have time to investigate this? (you disabled issues on your fork of the repo, that's why I'm writing this here.)

**Comment by sacabuche** [comment]
@timflutre sure I wiil try to check on this, can you open the issue in my fork? also if you have a sample I will be glad to use it.

**Comment by sacabuche** [comment]
@timflutre I added support for text in multiple lines, I hope is the only that is in multiple lines

**Comment by shapiromatron** [comment]
Any update on the status of this PR? Is anyone working on it? It looks like a pretty serious rewrite and behavior also changes significantly. Can I help get this moving somehow?

**Comment by MrTango** [comment]
I merged this. But as I'm currently not using the parser, feel free to take over.
If you nned access to pypi for a release, let me know.

**Comment by shapiromatron** [comment]
thanks @MrTango!  I would be willing to take over managing this project on pypi if you wish, we use pretty heavily in our work. Might be good to hear if @sacabuche is ok and if others have thoughts.

**Comment by sacabuche** [comment]
hi @MrTango and @shapiromatron for me is ok if @shapiromatron wants to take over. I'm not using this library anymore.

**Comment by timflutre** [comment]
same for me

**Comment by MrTango** [comment]
@shapiromatron your pypi username is shapiromatron too?

**Comment by shapiromatron** [comment]
Yep sure is. Thanks!

**Comment by MrTango** [comment]
@sacabuche you are now maintainer of this page, have fun ;)

**Comment by shapiromatron** [comment]
@MrTango Thank you! Confirmed; I have access on pipy. Do you want to transfer ownership of this github repository to myself, or may I have contributor access to this github repository? Or do you want me to just fork?  Or, I can submit PRs w/ the current process, but since I'm the only one using...

**Comment by MrTango** [comment]
@shapiromatron you are contributor now.
I if you need anything else, let me know.

**Pull request merged**
